import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function BlogPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Blog page</p>
    </div>
  );
}
