import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSession, signIn } from "next-auth/react";

export default function DashboardPage() {
  const { data: session, status } = useSession();

  if (status === "loading" || status === "unauthenticated" || !session) {
    return (
      <div>
        <button
          className={styles.signinButton}
          onClick={(e) => {
            e.preventDefault();
            signIn("github");
          }}
        >
          Sign in
        </button>
        to view dashboard
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Dashboard</p>
    </div>
  );
}
